### ISSUE TITLE
页面加载过慢

### ISSUE THREAD

**Issue by mtrucc** [sayPink/IronMan#2]
![image](https://user-images.githubusercontent.com/16724665/63162207-8bfe5e80-c054-11e9-8273-da12baf0b712.png)
看上去有很多的资源加载失败

**Comment by sayPink** [comment]
虽然没有看懂，但是本地不至于很慢，服务器接口（带宽有限1M，暂时只做了 gzip压缩）

**Comment by mtrucc** [comment]
too long time later..
